/**
 * Permission for staff DUNNIO ERP
 * @Public
 */
module.exports = {
    /** for material */
    MATERIAL_LIST: 'MATERIAL_LIST',
    MATERIAL_DETAIL: 'MATERIAL_LIST',
    MATERIAL_CREATE: 'MATERIAL_CREATE',
    MATERIAL_UPDATE: 'MATERIAL_UPDATE',
    MATERIAL_DELETE: 'MATERIAL_LIST',

    /** for order */
    ORDER_LIST: 'ORDER_LIST',
    ORDER_DETAIL: 'ORDER_LIST',
    ORDER_CREATE: 'ORDER_CREATE',
    ORDER_UPDATE: 'ORDER_UPDATE',
    ORDER_DELETE: 'ORDER_DELETE',
    ORDER_PAYMENT: 'ORDER_PAYMENT',

    /** for item */
    ITEM_LIST: 'ITEM_LIST',
    ITEM_DETAIL: 'ITEM_LIST',
    ITEM_CREATE: 'ITEM_CREATE',
    ITEM_UPDATE: 'ITEM_UPDATE',
    ITEM_DELETE: 'ITEM_DELETE',

    /** for item production */
    ITEM_ASSIGN: 'ITEM_ASSIGN',

    /** for production */
    DELIVERY_LIST: 'DELIVERY_LIST',
    DELIVERY_CREATE: 'DELIVERY_CREATE',
    DELIVERY_DETAIL: 'DELIVERY_LIST',
    DELIVERY_UPDATE: 'DELIVERY_UPDATE',

    /** for delivery */
    PRODUCTION_LIST: 'PRODUCTION_LIST',
    PRODUCTION_ASSIGN: 'PRODUCTION_ASSIGN',
    PRODUCTION_UPDATE: 'PRODUCTION_UPDATE',
    PRODUCTION_DETAIL: 'PRODUCTION_LIST',

    /** for promotion */
    PROMOTION_LIST: 'PROMOTION_LIST',
    PROMOTION_CREATE: 'PROMOTION_CREATE',
    PROMOTION_DETAIL: 'PROMOTION_LIST',
    PROMOTION_UPDATE: 'PROMOTION_UPDATE',
    PROMOTION_DELETE: 'PROMOTION_DELETE',
    PROMOTION_PROCESS: 'PROMOTION_PROCESS',

    /** for type */
    MATERIAL_TYPE_LIST: 'MATERIAL_TYPE_LIST',
    MATERIAL_TYPE_DETAIL: 'MATERIAL_TYPE_LIST',
    MATERIAL_TYPE_CREATE: 'MATERIAL_TYPE_CREATE',
    MATERIAL_TYPE_UPDATE: 'MATERIAL_TYPE_UPDATE',
    MATERIAL_TYPE_DELETE: 'MATERIAL_TYPE_DELETE',

    /** for attribute */
    MATERIAL_ATTRIBUTE_LIST: 'MATERIAL_ATTRIBUTE_LIST',
    MATERIAL_ATTRIBUTE_DETAIL: 'MATERIAL_ATTRIBUTE_LIST',
    MATERIAL_ATTRIBUTE_CREATE: 'MATERIAL_ATTRIBUTE_CREATE',
    MATERIAL_ATTRIBUTE_UPDATE: 'MATERIAL_ATTRIBUTE_UPDATE',
    MATERIAL_ATTRIBUTE_DELETE: 'MATERIAL_ATTRIBUTE_DELETE'
};
